## mysql配置文件
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-test-config
  namespace: test
  labels:
    app: mysql-test
data:
  my.cnf: |-
    [client]
    socket=/var/run/mysqld/mysqld.sock
    [mysql]
    default-character-set=utf8mb4
    [mysqld] 
    host-cache-size=0
    skip-name-resolve
    datadir=/var/lib/mysql
    socket=/var/run/mysqld/mysqld.sock
    secure-file-priv=/var/lib/mysql-files
    user=mysql
    sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER
    lower_case_table_names=1
    pid-file=/var/run/mysqld/mysqld.pid
    tls_version=TLSv1.2,TLSv1.3

---

## PV
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: mysql-test-pv
#  labels:
#    app: mysql-test             #设置 pv 的 label 标签
#spec:
#  capacity:
#    storage: 25Gi          #设置 pv 存储资源大小
#  accessModes:
#    - ReadWriteOnce
#  mountOptions:
#    - hard
#    - nfsvers=4.1
#  csi:
#    driver: nasplugin.csi.alibabacloud.com
#    volumeAttributes:
#      path: ''
#      server: mysql-test-domain
#    volumeHandle: mysql-test
#  persistentVolumeReclaimPolicy: Delete
---

## PVC
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: mysql-test-pvc
#spec:
#  resources:
#    requests:
#      storage: 50Gi        #设置 pvc 存储资源大小
#  accessModes:
#    - ReadWriteOnce
#  selector:
#    matchLabels:
#      app: mysql-test           #根据 Label 选择对应 PV

---
## Service
#apiVersion: v1
#kind: Service
#metadata:
#  name: mysql-test
#  labels:
#    app: mysql-test
#spec:
#  type: NodePort
#  ports:
#    - name: mysql
#      port: 33060 #服务对外端口
#      targetPort: 3306 #容器端口
#      nodePort: 30001 #主机端口
#  selector:
#    app: mysql-test

---

## Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-test
  labels:
    app: mysql-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-test
  template:
    metadata:
      labels:
        app: mysql-test
    spec:
      containers:
        - name: mysql
          image: registry.cn-hangzhou.aliyuncs.com/aliyun_name_space_ly/mysql:8.0.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD    ## 配置Root用户默认密码
              value: "eAxMaROSaDd9"
#          resources:
#            limits:
#              cpu: 2000m
#              memory: 512Mi
#            requests:
#              cpu: 2000m
#              memory: 512Mi
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            exec:
              command: [ "mysqladmin", "-uroot", "-p${MYSQL_ROOT_PASSWORD}", "ping" ]
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            exec:
              command: [ "mysqladmin", "-uroot", "-p${MYSQL_ROOT_PASSWORD}", "ping" ]
          volumeMounts:
            - name: mysql-log
              mountPath: /var/log
              subPath: data/log
            - name: config
              mountPath: /etc/mysql/conf.d/my.cnf
              subPath: my.cnf
            - name: mysql-data
              mountPath: /var/lib/mysql
              subPath: data/mysql/data
            - name: mysql-files
              mountPath: /var/lib/mysql-files
              subPath: data/mysql/mysql-files
            - name: localtime
              readOnly: true
              mountPath: /etc/localtime
      volumes:
        - name: mysql-log
          persistentVolumeClaim:
            claimName: pvc-mysql-log
        - name: mysql-data
          persistentVolumeClaim:
            claimName: pvc-mysql-data
        - name: mysql-files
          persistentVolumeClaim:
            claimName: pvc-mysql-files
        - name: config
          configMap:
            name: mysql-test-config
        - name: localtime
          hostPath:
            type: File
            path: /etc/localtime
      imagePullSecrets:
        - name: aliyun-acr