

## PV
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: rabbitmq-test-pv
#  labels:
#    app: rabbitmq-test             #设置 pv 的 label 标签
#spec:
#  capacity:
#    storage: 25Gi          #设置 pv 存储资源大小
#  accessModes:
#    - ReadWriteOnce
#  mountOptions:
#    - hard
#    - nfsvers=4.1
#  csi:
#    driver: nasplugin.csi.alibabacloud.com
#    volumeAttributes:
#      path: ''
#      server: rabbitmq-test-domain
#    volumeHandle: rabbitmq-test
#  persistentVolumeReclaimPolicy: Delete
---

## PVC
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: rabbitmq-test-pvc
#spec:
#  resources:
#    requests:
#      storage: 50Gi        #设置 pvc 存储资源大小
#  accessModes:
#    - ReadWriteOnce
#  selector:
#    matchLabels:
#      app: rabbitmq-test           #根据 Label 选择对应 PV

---
## Service
#apiVersion: v1
#kind: Service
#metadata:
#  name: rabbitmq-test
#  labels:
#    app: rabbitmq-test
#spec:
#  type: NodePort
#  ports:
#    - name: rabbitmq
#      port: 33060 #服务对外端口
#      targetPort: 3306 #容器端口
#      nodePort: 30001 #主机端口
#  selector:
#    app: rabbitmq-test

---

## Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-test
  labels:
    app: rabbitmq-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-test
  template:
    metadata:
      labels:
        app: rabbitmq-test
    spec:
      containers:
        - name: rabbitmq
          image: registry.cn-hangzhou.aliyuncs.com/aliyun_name_space_ly/rabbitmq:3-delayed
          ports:
            - containerPort: 4369
              protocol: TCP
            - containerPort: 5672
              protocol: TCP
            - containerPort: 25672
              protocol: TCP
            - containerPort: 15672
              protocol: TCP
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "rabbit"
            - name: RABBITMQ_DEFAULT_PASS
              value: "oPtxPmadCR2H"
#          resources:
#            limits:
#              cpu: 2000m
#              memory: 512Mi
#            requests:
#              cpu: 2000m
#              memory: 512Mi
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq #容器内目录
              subPath: data/rabbitmq/data
            - name: localtime
              readOnly: true
              mountPath: /etc/localtime
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: pvc-rabbitmq-data
        - name: localtime
          hostPath:
            type: File
            path: /etc/localtime
      imagePullSecrets:
        - name: aliyun-acr